### ISSUE TITLE
android users was not stable in the room

### ISSUE THREAD

**Issue by ehsanwwe** [adrenak/univoice#10]
my android client
left the chat without any error
i just see a log
he left the room
but the client doesn't press any buttons

an example Error :
`AndroidPlayer(HUAWEI_JKM-LX1@192.168.1.180) You left the chatroom`

all of the clients are in LAN

**Comment by adrenak** [comment]
@ehsanwwe the inbuilt network implementation based on airpeer library is pretty old and not very stable due to issues with airpeer itself.

What I would recommend is making a LAN implementation of the `IChatroomNetwork` interface and use that as the network.

The inbuilt (airpeer) implementation is here: https://github.com/adrenak/univoice/blob/master/Assets/Adrenak.UniVoice/InbuiltImpl/AirPeerUniVoiceNetwork.cs

It's not too long, less than 150 lines. Much of the code will be similar. I'd recommend Telepathy.

If you decide to make this and are ok with sending a PR, I'd appreciate it. It'll be a while before I make it myself and others could also use this feature.
