### ISSUE TITLE
peers on different networks are often unable to connect.，is this problem solved?

### ISSUE THREAD

**Issue by Arsterlowar** [adrenak/univoice#13]

**Comment by adrenak** [comment]
No that unfortunately is an issue that's not been addressed. The problem seems to be at NAT punching level. You might want to check out com.unity.webrtc (or OpenNAT) and make your own networking implementation based on them, leaving univoice to only do the audio stuff.

**Comment by julian-innerchild** [comment]
@adrenak So using an alternative backend for establishing the connection, like going with some relay server could solve this 100% connectivity issue, or have I misunderstood?

**Comment by adrenak** [comment]
@julian-innerchild yes iiuc. Do keep in mind that univoice uses airpeer, which uses airsignal (JS running on cloud) all these are repos on my profile if you need to have a look.

You can directly replace airpeer with unity's webrtc, for example. You'd need to make an IChatroomNetwork implementation that uses unity's webrtc. Then use that instead of AirPeerUniVoiceNetwork, which is the default implementation in the repository.

**Comment by saeed30** [comment]
I have connection issue when peers are not in the same network. Anybody has IChatroomNetwork implementation that uses unity's webrtc?
