### ISSUE TITLE
Does univoice support IL2CPP?

### ISSUE THREAD

**Issue by lukechatton** [adrenak/univoice#34]
The readme doesn't mention IL2CPP support. I'm hoping that's included here. 

Thank you :)

**Comment by adrenak** [comment]
Hi @lukechatton 

Univoice doesn't have any native libraries of its own, so it is IL2CPP compatible. However, do note that an older network implementation based on a library named AirPeer is _not_ since its native libs are mono only

If you're planning to use Mirror, Telepathy, etc you should be fine. IL2CPP compatibility would just depend on the underlying networking solution you plan to use
